//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Actor
{
    public int Id { get; set; }
    public string ActorName { get; set; }
    public Nullable<int> ActorTypeId { get; set; }
    public Nullable<int> LanguageId { get; set; }

    public virtual ActorType ActorType { get; set; }
    public virtual Language Language { get; set; }
}

public partial class ActorType
{
    public ActorType()
    {
        this.Actors = new HashSet<Actor>();
    }

    public int Id { get; set; }
    public string TypeName { get; set; }

    public virtual ICollection<Actor> Actors { get; set; }
}

public partial class Language
{
    public Language()
    {
        this.Actors = new HashSet<Actor>();
        this.Videos = new HashSet<Video>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Actor> Actors { get; set; }
    public virtual ICollection<Video> Videos { get; set; }
}

public partial class Video
{
    public Video()
    {
        this.VideoShopItems = new HashSet<VideoShopItem>();
    }

    public int Id { get; set; }
    public string YoutubeID { get; set; }
    public string VideoName { get; set; }
    public Nullable<int> LanguageId { get; set; }
    public string ActorIds { get; set; }
    public Nullable<int> VideoTypeId { get; set; }

    public virtual Language Language { get; set; }
    public virtual VideoType VideoType { get; set; }
    public virtual ICollection<VideoShopItem> VideoShopItems { get; set; }
}

public partial class VideoShopItem
{
    public int Id { get; set; }
    public decimal PTop { get; set; }
    public decimal PLeft { get; set; }
    public Nullable<decimal> StartTime { get; set; }
    public Nullable<decimal> EndTime { get; set; }
    public Nullable<int> Video_Id { get; set; }
    public string ProductHandle { get; set; }

    public virtual Video Video { get; set; }
}

public partial class VideoType
{
    public VideoType()
    {
        this.Videos = new HashSet<Video>();
    }

    public int Id { get; set; }
    public string TypeName { get; set; }

    public virtual ICollection<Video> Videos { get; set; }
}
