//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappiPugService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieItem
    {
        public int Id { get; set; }
        public Int64 ProductNo { get; set; }
        public string ProductName { get; set; }
        public string ProductShopURL { get; set; }
        public string ProductImgURL { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public decimal ptop { get; set; }
        public decimal pleft { get; set; }
        public decimal starttime { get; set; }
        public decimal endtime { get; set; }
        public Nullable<int> Movie_Id { get; set; }
        public string ProductHandle { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
