//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappiPugCloudService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.VideoShopItems = new HashSet<VideoShopItem>();
        }
    
        public int Id { get; set; }
        public string YoutubeID { get; set; }
        public string VideoName { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string ActorIds { get; set; }
        public Nullable<int> VideoTypeId { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual VideoType VideoType { get; set; }
        public virtual ICollection<VideoShopItem> VideoShopItems { get; set; }
    }
}
